# Generated by Django 5.1.2 on 2024-12-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('registered_credit_card', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('employe_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
                ('contact', models.JSONField()),
                ('adresse', models.JSONField()),
                ('date_embauche', models.DateField()),
                ('competences', models.JSONField()),
                ('mdp', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('fournisseur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.JSONField()),
                ('adresse', models.JSONField()),
                ('materiel_fournit', models.CharField(blank=True, max_length=255, null=True)),
                ('usine_livree', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('delivery_option', models.CharField(choices=[('Express', 'Express'), ('Standard', 'Standard')], max_length=8)),
                ('delivery_address', models.CharField(max_length=100)),
                ('delivery_postal_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=10)),
                ('delivery_mode', models.CharField(choices=[('Train', 'Train'), ('Airplane', 'Airplane'), ('Truck', 'Truck'), ('Ship', 'Ship')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_card', models.CharField(max_length=16)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistoriqueVentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.client')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('planning_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Matin', 'Matin'), ('Après-midi', 'Après-midi'), ('Nuit', 'Nuit')], max_length=10)),
                ('commentaires', models.TextField()),
                ('employes_assignes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.employe')),
                ('produits_prepares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_production', models.DateField()),
                ('quantite_produite', models.IntegerField()),
                ('temps_de_production', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Terminé', 'Terminé'), ('En cours', 'En cours'), ('Annulé', 'Annulé')], max_length=10)),
                ('commentaires', models.TextField()),
                ('planning_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.planning')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('cheese_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitOrderHistorique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historiqueventes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderhistoriqueventes')),
                ('produits_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SousTraitant',
            fields=[
                ('sous_traitant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.JSONField()),
                ('adresse', models.JSONField()),
                ('services_fournis', models.JSONField()),
                ('produits_traites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price_per_bottle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.planning')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
            ],
            options={
                'unique_together': {('planning', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='OrderStockProduct',
            fields=[
                ('stockproduct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
