# Generated by Django 5.0.4 on 2024-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produitpreparation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='produitpreparation',
            constraint=models.UniqueConstraint(fields=('planning', 'produit'), name='unique_planning_produit'),
        ),
    ]
